openapi: 3.0.0
info:
  description: >-
    Firefly Service's RESTful InDesign APIs (beta) offer resources to automate tedious, 
    time-consuming design tasks through scalable cloud services, 
    encouraging more personalization at scale, creative automation, 
    and faster content delivery. 
  version: 0.1.0
  title: Firefly Services - InDesign APIs (beta)
  contact:
    email: idservices@adobe.com
tags:
  - name: Data Merge API
    description: The Data Merge API is used to create document variations from data and to extract data merge tags. 
security:
  - ApiKeyAuth: []
  - BearerAuth: []
paths:
  /v3/merge-data:
    $ref: paths/v3_merge-data.yaml
  /v3/merge-data-tags:
    $ref: paths/v3_merge-data-tags.yaml
servers:
  - url: https://indesign.adobe.io
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
