openapi: 3.0.0
info:
  description: >-
    Firefly Service's RESTful InDesign APIs (beta) offer resources to automate tedious, 
    time-consuming design tasks through scalable cloud services, 
    encouraging more personalization at scale, creative automation, 
    and faster content delivery.  
  version: 0.1.0
  title: Firefly Services - InDesign APIs (beta)
  contact:
    email: idservices@adobe.com
tags:
  - name: Capabilities API
    description: >-
      The Capabilities API allows you to submit custom capabilities 
      to do almost anything you can do in InDesign using a custom script.
      You can also check the status of an executed capability.
security:
  - ApiKeyAuth: []
  - BearerAuth: []
paths:
  /v3/status/{id}:
    $ref: paths/v3_status_{id}.yaml
  /v3/capability:
    $ref: paths/v3_capability.yaml
  /v3/{organization}/{capability}:
    $ref: paths/v3_{organization}_{capability}.yaml
servers:
  - url: https://indesign.adobe.io
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
